### ISSUE TITLE
Add a parameter for retrieving the entity attribute from the request instead of `request.user`

### ISSUE THREAD

**Issue by koladev32** [koladev32/djangorestframework-simple-apikey#20]
For the moment, we are using `request.user` to retrieve the entity attached to the API key. For a better developer experience, we are planning to retrieve the entity from `request.entity` instead of `request.user`. 
The catch here is that we should also allow the user to set the attribute on the request object. Meaning that we would do something like:

```python
entity = getattr(request, settings.SIMPLE_API_KEY["REQUEST_ENTITY_ATTRIBUTE"], None)
```

To discuss surely.

**Comment by koladev32** [comment]
cc @Ederene20

**Comment by Ederene20** [comment]
Cc @koladev32, currently working on it. I'll create a PR soon.
