### ISSUE TITLE
Bug when generating a fernet key using django-admin command

### ISSUE THREAD

**Issue by koladev32** [koladev32/djangorestframework-simple-apikey#33]
**Describe the bug**
In the documentation, it is stated that we can create a fernet key using the following command

```shell
django-admin generate_fernet_key
```

**To Reproduce**
1. Create a Django project and install the project.
2. Run the command `django-admin generate_fernet_key`
3. See the error

**Expected behavior**

The command should actually return a fernet key, like when we use the `python manage.py generate_fernet_key` command.

**Screenshots**

<img width="837" alt="image" src="https://user-images.githubusercontent.com/32314456/221385861-2c70cdb9-b8b6-480c-bb41-2d379622a423.png">

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.2 (22D49)
 - Python Version: 3.11
 - Django Version: 4.1.7
 - Package: 0.1.0

**Comment by Ederene20** [comment]
Thank you for reporting the bug @koladev32. After carefully reading the part of Django official documentation which explains how to create a custom command, I think that we can only use the `python manage.py generate_fernet_key` command.

[The following quote is from an example in the documentation.](https://docs.djangoproject.com/en/4.1/howto/custom-management-commands/#)
> The new custom command can be called using python manage.py closepoll <poll_ids>.

We are going to remove `django-admin generate_fernet_key` from the doc fand use `python manage.py generate_fernet_key` for now.
